NODES="ose3-master1.test.example.com ose3-master2.test.example.com ose3-master3.test.example.com"
NODES="$NODES ose3-node1.test.example.com ose3-node2.test.example.com"
NODES="$NODES ose3-node3.test.example.com ose3-node4.test.example.com"
NODES="$NODES ose3-node5.test.example.com ose3-node6.test.example.com"
#NODES="$NODES ose3-node7.test.example.com ose3-node8.test.example.com"
#NODES="$NODES ose3-node9.test.example.com ose3-node10.test.example.com"
NODES="$NODES ose3-infra1.test.example.com ose3-infra2.test.example.com"
NODES="$NODES ose3-lb.test.example.com"
NODES="$NODES ose3-ansible.test.example.com"

